### ISSUE TITLE
all monitor blank when set use discrete NVIDA gpu as priamary

### ISSUE THREAD

**Issue by kimsoso** [hyprwm/aquamarine#115]
My laptop is intel nuc X15 with intel and nvida hybrid env.
bcz my internal gpu has low performance when use external monitor, so i want to use NVIDIA as primary,

gpu as below shows(card1 is intel i915 on gen11, card0 is NVIDIA 3070):
lrwxrwxrwx - root 13 12月 14:17 pci-0000:00:02.0-card -> ../card1
lrwxrwxrwx - root 13 12月 14:17 pci-0000:00:02.0-render -> ../renderD129
lrwxrwxrwx - root 13 12月 14:17 pci-0000:01:00.0-card -> ../card0
lrwxrwxrwx - root 13 12月 14:17 pci-0000:01:00.0-render -> ../renderD128

when i set env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0

can't start hyprland, and come back to login screen after 3 secs.

**Comment by vaxerski** [comment]
backfeeding from nvidia to igpu powered displays is physically impossible, that's likely why you get black screens. You may have some luck if you have a hardware MUX switch.
