### ISSUE TITLE
Explicit_sync: external monitor

### ISSUE THREAD

**Issue by Ciflire** [hyprwm/aquamarine#23]
With explicit sync on I have the following graphic bug that i cannot capture on obs or smth like that

https://github.com/user-attachments/assets/73e0f88b-4410-4929-b093-4c8b179d6ca1

I don't know what to provide more than that, it's a glitch that already was in sway, exact same glitch, on the same portion of the screen. This is not a connectivity or screen issue I tried to change both, same result. Same problem if i try using usb-c-dp port.

**Comment by Ciflire** [comment]
After a little investigation, this is the same behaviour as if i had disable the `nvidia_anti_flicker` option

**Comment by Ciflire** [comment]
update: the kms explicit sync only reproduces this bug

**Comment by vaxerski** [comment]
what does that even mean

**Comment by Ciflire** [comment]
the bug i'm metionning only happens with this config
```
render {
  explicit_sync = 1
  explicit_sync_kms = 1
}
```
and not with `explicit_sync_dkms` unset (so default value is 2 iirc)
