### ISSUE TITLE
[BUG] Reserve workspace works only horizontally...

### ISSUE THREAD

**Issue by grappas** [hyprwm/aquamarine#24]
For both horizontal and vertical reservation request from status bars
![obraz](https://github.com/user-attachments/assets/df4a7b1b-d958-45db-ab30-f254413f062d)
in attached image eww reserves vertical space, but hyprland gives it horizontal :)

**Comment by vaxerski** [comment]
how is this an aquamarine issue

open an issue at hl and bisect

**Comment by grappas** [comment]
You just fixed it ¯\_(ツ)_/¯

Thanks anyway.
