### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by bubba-champion** [hyprwm/aquamarine#28]
Literally the same issue as https://github.com/hyprwm/aquamarine/issues/26, but I'm on AMD.

**Comment by vaxerski** [comment]
are you on latest aq-git? I thought I fixed this.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/16367029/patch.txt)
try this patch @darkwater @bubba-champion

**Comment by darkwater** [comment]
Works with the patch
