### ISSUE TITLE
Follow symlinks AQ_DRM_DEVICES

### ISSUE THREAD

**Issue by sjcobb2022** [hyprwm/aquamarine#33]
Currently the AQ_DRM_DEVICES does not accept symlinks as an input, it expects the absolute path.

This is an issue, as the card number (`card0`, `card1` etc.) can change after updates. 

Previously with wlroots, it was possible to specify a symlink to the proper card (using dev/dri/by-path/pci-0000:0X:00.0-card).

I am working on a pull request to determine whether this function works.

**Comment by sjcobb2022** [comment]
Awesome, super easy to implement. Opening PR.

**Comment by vaxerski** [comment]
it should just work...

**Comment by sjcobb2022** [comment]
Yeh, it works for me. How are you adding the env var?

The env var cannot have any colons in it.
