### ISSUE TITLE
Integrating features from Louvre

### ISSUE THREAD

**Issue by ThousandDemonDaggers** [hyprwm/aquamarine#39]
Since Hyprand has now more freedom regarding the development of the compositor library could be a good idea to also look at some features of [Louvre](https://github.com/CuarzoSoftware/Louvre).

**Comment by vaxerski** [comment]
like? louvre is a different library with different goals

**Comment by ThousandDemonDaggers** [comment]
> like? louvre is a different library with different goals

Yes, I know. However what I really meant is that maybe there is the possibility of taking inspiration from it in some aspects. But yeah, you are definitely right.

**Comment by vaxerski** [comment]
> of taking inspiration from it in some aspects

in what aspects?!
