### ISSUE TITLE
Tearing DRM commits break VRR

### ISSUE THREAD

**Issue by BluewyDiamond** [hyprwm/aquamarine#41]
I have noticed that my monitor refresh rate is stuck at ~48-78hz despite my fullscreen game is running well over 144 fps.

According to the bisect this commit is the culprit 18c6a8ccaf6f17264f153440703cab9feae47988.

**Comment by vaxerski** [comment]
tearing enabled? what if you disable

**Comment by BluewyDiamond** [comment]
yes i have tearing enabled and disabling tearing will make my refresh rate look normal

**Comment by BluewyDiamond** [comment]
any updates?

**Comment by vaxerski** [comment]
no, I'm currently working on other stuff. I'd recommend not using tearing for the moment if it's broken (or, well, make a MR to fix it :) )

**Comment by BluewyDiamond** [comment]
tearing + vrr works again, but sometimes my whole system freezes (have to force power down + it does not generate a hyprland crash log, coredumpctl only shows something about steam and proton-ge) this does not happend if i disable tearing in the config
