### ISSUE TITLE
Error building on Ubuntu 24.04

### ISSUE THREAD

**Issue by vaskark** [hyprwm/aquamarine#43]
Hi. I'm trying to build this on Ubuntu 24.04 and get this error:

```
[100%] Linking CXX executable simpleWindow
/usr/bin/ld: libaquamarine.so.0.3.0: undefined reference to `libinput_device_get_id_bustype'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/simpleWindow.dir/build.make:111: simpleWindow] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:894: CMakeFiles/simpleWindow.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```
Can anyone offer some help?
Thanks.

Ubuntu: 24.04
Hyprland: 0.41.2 (binary)

**Comment by vaxerski** [comment]
you need libinput >= 1.26

**Comment by vaskark** [comment]
I installed libinput 1.26 in /usr/local. Shouldn't that work?

**Comment by vaxerski** [comment]
if there is libinput installed in /usr it will likely have precedence. I don't know your system, but I see your libinput is too old.

**Comment by dielburg** [comment]
@vaskark if you installed libinput earlier using apt try apt-get remove. Just build latest libinput from git.

It works for me, cuz I had case similar to yours (ubuntu 24.04)

**Comment by vaskark** [comment]
> @vaskark if you installed libinput earlier using apt try apt-get remove. Just build latest libinput from git.
> 
> 
> 
> It works for me, cuz I had case similar to yours (ubuntu 24.04)

Thanks for responding. I did install libinput (git) to /usr and things work fine now. I wish it was an easier process getting it all to work on Ubuntu, though. Maybe someday :)

**Comment by dielburg** [comment]
@vaskark did you have problem with xcb_errors.h during compilation latest version of Hyprland?

**Comment by vaskark** [comment]
@dielburg Yes I did. Here's what happened:

On my old laptop, I built libxcb-errors and it worked fine. When I tried to do the same on my new laptop, for some reason I couldn't check the code out (don't recall the error). So I was left to copy the software folder over to the new machine and build it there. Didn't know how else to solve that. So I have it, anyway. Not sure if the libxcb-errors repo is still experiencing difficulties.

**Comment by vaskark** [comment]
@dielburg I've just tried to build libxcb-errors again and I'm having the same problem. It asks me to run `git submodule update --init` and it's stalling.

**Comment by dielburg** [comment]
I discovered that the problem is with m4 dependency. Git submodule command cannot reach the git://anongit.freedesktop.org/xcb/util-common-m4.git.

Sometimes I was able to open this in web browser but I was not able to download anything.

@vaskark Can you upload on git your libxcb-errors files with this m4 included? You said that you have these files from your build on old computer.

**Comment by vaskark** [comment]
@dielburg I was working on doing just that but the m4 part isn't being uploaded. I'm going to have to compress the folder and email it. Or post it to a download site somewhere. Any prefs or ideas?

**Comment by vaskark** [comment]
@dielburg [link](https://drive.google.com/file/d/19WdK9wii0TiiUX6slopwasLMrPTniYCc/view?usp=sharing)

**Comment by dielburg** [comment]
Works great! Thank you so much for help. Hope this issue with libxcb-errors will be fixed soon aby the authors.

**Comment by vaskark** [comment]
@dielburg No problem. Glad to help. Even though, looking back through this thread, I could have made my answer a lot more straightforward. Lack of sleep.

Be well.
