### ISSUE TITLE
Monitors attached to the 2º GPU are ignored

### ISSUE THREAD

**Issue by Zeioth** [hyprwm/aquamarine#45]
## Short description
Out of my 6 monitors, only the 3 attached to the first GPU turn on.

## Details
Everything was working fine until I upgraded from hyprland stable to hyprland-git (with aquamarine) today. I've read the docs [A](https://wiki.hyprland.org/Configuring/Multi-GPU/) and [B](https://wiki.hyprland.org/Configuring/Environment-variables/) so I made the required change from

```
WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0
```

to
```
AQ_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0
```

`hyprctl monitors` can list all my monitors correctly, it is just they don't turn on anymore.

![screenshot_2024-08-10_23-34-29_798234812](https://github.com/user-attachments/assets/f8882566-0b04-4eda-b697-141340398107)

## Logs 
Using `Hyprland > mylog` from TTY with `HYPRLAND_TRACE=1`.
https://pastebin.com/raw/fubmZ0Ji

(Nothing super remarkable here)

**Comment by Zeioth** [comment]
also I haven't changed the config file, it is the same one as usual:
https://github.com/Zeioth/zeioth-hyprland-config

**Comment by romanstingler** [comment]
probably related to #40

**Comment by romanstingler** [comment]
can you try building all packages new. 
Something like this.
Meanwhile, I guess most outputs except Thunderbolt should be fixed/

`yay -S aquamarine-git hyprlang-git hyprcursor-git hyprutils-git hyprland-git --overwrite="*" `

**Comment by Zeioth** [comment]
@romanstingler yes i can test give me a sec

**Comment by Zeioth** [comment]
Issue remains

**Comment by romanstingler** [comment]
please build ` yay -S hyprland-git aquamarine-git` new and add `env = AQ_NO_MODIFIERS,1` to your `hyperland.conf`

**Comment by Zeioth** [comment]
Issue remains.

**Comment by Zeioth** [comment]
I've debugged this a bit more and it woks fine when the GPUs are passed in the default order.
```
AQ_DRM_DEVICES=/dev/dri/card0:/dev/dri/card1
```

Doing the opposite is what causes one of the GPUs to be ignored
```
AQ_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0
```

**Comment by Zeioth** [comment]
The point is to be able to decide what GPU commands what monitors. This is important because the monitors attached to the secondary GPU will max 30 FPS (this also happened in wlroots).

**Comment by vaxerski** [comment]
is card1 nvidia? Reverse-feeding from nvidia to an igpu of any brand is physically impossible due to hardware limitations

**Comment by Zeioth** [comment]
@vaxerski both AMD.
![screenshot_2024-09-14_11-00-02_371730347](https://github.com/user-attachments/assets/b23e4965-c5e9-4587-986c-6c5f1a3437dd)

**Comment by Zeioth** [comment]
@vaxerski I've been able to discover the root issue by buying a new GPU. As I suspected: 

* The transition to Aquamarine [has removed support for this feature on any GPU older than AMD GFX9](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/2771#note_1143189).
* This issue also existed in wlroots, but only when `WLR_RENDERER=vulkan`.

So this is not a bug, this is the minimum spec requirement for AMD gpus using multi GPU, and we should probably maybe indicate it on the hyprland manual [here](https://wiki.hyprland.org/Configuring/Multi-GPU/).

**Comment by Zeioth** [comment]
This one can be closed once we document.
