### ISSUE TITLE
AQ_DRM_DEVICES is undocumented

### ISSUE THREAD

**Issue by LazarusCat59** [hyprwm/aquamarine#47]
Currently in `docs/env.md`, `AQ_DRM_DEVICES` is not mentioned, but on my setup atleast setting `env = AQ_DRM_DEVICES,/dev/dri/card0:/dev/dri/card1` does make it render on my NVIDIA dGPU for my external monitor.

**Comment by romanstingler** [comment]
[AQ_DRM_DEVICES](https://wiki.hyprland.org/Configuring/Multi-GPU/#telling-hyprland-which-gpu-to-use)

**Comment by LazarusCat59** [comment]
> [AQ_DRM_DEVICES](https://wiki.hyprland.org/Configuring/Multi-GPU/#telling-hyprland-which-gpu-to-use)

Ah apologies, I did not look through the Hyprland documentation, only Aquamarine's. But isn't it still a good idea to document it at `docs/env.md`?

**Comment by vaxerski** [comment]
good idea
