### ISSUE TITLE
Custom modeline from wlroots doesn't work anymore

### ISSUE THREAD

**Issue by Cherenkov11** [hyprwm/aquamarine#53]
Hello

I have an Asus monitor that by default goes up to 1080p@240Hz but can be overclocked to 280Hz, but it uses a nonstandard timing that Wayland doesn't detect. I can workaround this by using a custom modeline:

`monitor = DP-1, modeline 628.00 1920 1968 2028 2040 1080 1090 1092 1100 +hsync -vsync, 0x0, 1`

After restarting hyprland with this modeline, the resolution end up in a random mode 720x400@70Hz. I used to use this modeline before the migration to aquamarine and it worked perfectly fine.

This is what I get after uncomment the monitor setting while running hyprland. (with hyprctl rollinglog -f) but the mode doesn't change.

`[LOG] Applying monitor rule for DP-1
[LOG] Set a custom mode 1920x1080@279.856995 (mode not found in monitor modes)
[LOG] output DP-1 succeeded basic test on format DRM_FORMAT_XRGB8888
[LOG] [AQ] drm: Modesetting DP-1 with 1920x1080@239.76Hz
[ERR] [AQ] drm: Cannot commit when a page-flip is awaiting
[ERR] Couldn't commit output named DP-1
[LOG] arrangeMonitors: 1 to arrange
[LOG] arrangeMonitors: DP-1 explicit [0, 0]
[LOG] arrangeMonitors: DP-1 xwayland [0, 0]
[LOG] Monitor DP-1 data dump: res 1920x1080@279.86Hz, scale 1.00, transform 0, pos 0x0, 10b 0`

Hope this is enough information of the issue, if more is needed just let me know.

Versions:
hyprland 0.42
aquamarine 0.3.2

**Comment by vaxerski** [comment]
its fixed in hyprland-git
