### ISSUE TITLE
Driver crash in clearBuffer in EGL with KVM/QEMU

### ISSUE THREAD

**Issue by mylinuxforwork** [hyprwm/aquamarine#56]
### Regression?

Yes

### System Info and Version

Cannot paste it because Hyprland isn't starting.

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Description

I cannot start Hyprland anymore on KVM VM.
No problems last week on any Arch based VM. 

### How to reproduce

Install Hyprland in a KVM VM (3D enabled) with sudo pacman -S hyprland
Hyprland don't start with sddm or tty anymore.

Created a VM from scratch with the latest Arch ISO 08/2024 + Hyprland profile. Same issue. sddm cannot start Hyprland and falls back. The same on tty.

### Crash reports, logs, images, videos

[hyprlandCrashReport69.txt](https://github.com/user-attachments/files/16659215/hyprlandCrashReport69.txt)

**Comment by mylinuxforwork** [comment]
> can someone post a trace log https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-trace-log
> 
> also moving to aquamarine

I will try.

**Comment by mylinuxforwork** [comment]
Set the environment variables and started Hyprland. Result.

![image](https://github.com/user-attachments/assets/829ba63f-a5b4-468d-b83c-10be6567d82d)

**Comment by mylinuxforwork** [comment]
Ok. I will check.

**Comment by mylinuxforwork** [comment]
Sorry. But it's not working. 

![image](https://github.com/user-attachments/assets/a6932ba4-9215-48f0-b780-2bfdb0a1ca02)

Maybe you have an idea?

**Comment by vaxerski** [comment]
uhhh why is .bash_history there?

You can just manually cd to the dir and find the most recent directory. log will be inside

**Comment by vaxerski** [comment]
try this

**Comment by vaxerski** [comment]
did it work?

**Comment by vaxerski** [comment]
aquamarine-git, might be fixed with the linked commit

**Comment by mylinuxforwork** [comment]
Do you know how to solve this dependency error?
![image](https://github.com/user-attachments/assets/d4fbf371-7777-4050-91b5-43d71afc7069)

I have installed it with 

yay -S aquamarine-git

**Comment by vaxerski** [comment]
`yay -R hyprland`
`yay -S aquamarine-git`
`yay -S hyprland`

**Comment by mylinuxforwork** [comment]
It is working again. Great.

But I had to install hyprland-git instead of hyprland. Could not install hyprland with aquamarine-git.

**Comment by vaxerski** [comment]
alright, great, closing then.

maybe hyprland-git has a hard dep on aq-git. I'll make an aq release soon
