### ISSUE TITLE
Monitor Recognition Issue with Dock Hub | No Signal

### ISSUE THREAD

**Issue by Da4ndo** [hyprwm/aquamarine#69]
## Problem Description

I'm experiencing an issue with the newest version of Hyprland using Aquamarine. The system doesn't recognize the LG 34WP65G-B monitor plugged into the [HAMA Dock Hub](https://www.mediamarkt.hu/hu/product/_hama-usb-3-2-type-c-10in1-dokkol%C3%B3-adapter-sz%C3%BCrke-200100-1375999.html?utm_content=1375999&gad_source=1) on my laptop, resulting in a black screen. Even running `hyprctl monitors all` doesn't show the monitor connected through the hub. However, when I plug the monitor directly into the HDMI port on the laptop, it recognizes it correctly. The problem is that I have two monitors, which is why I need to use the hub, but it doesn't work as expected.

I have one HDMI port on the laptop, and if I plug the monitor there, it recognizes it without issues. Unfortunately, this doesn't solve my problem as I need to connect two monitors simultaneously.

I've included logs from Hyprland, journalctl, and dmesg. These logs are from a session where I booted my laptop with the monitor connected directly to the laptop, then unplugged it, plugged it into the hub, checked the connection, and finally replugged it back into the port on the laptop. This should provide a comprehensive view of the system's behavior during these different connection scenarios.

Needless to say, I use the -git versions of the packages and I always try to keep them updated to the latest version. This issue first occurred approximately two weeks ago. I initially waited to see if it would be resolved in subsequent updates, but after no improvement, I've decided to create an issue on GitHub.

> **Note:** All testing and log collection was performed with only one monitor being unplugged and plugged. The second monitor is not connected during these tests to isolate the issue and simplify troubleshooting.

## System Specifications

- **Operating System**: Arch Linux x86_64
- **Kernel**: Linux 6.10.6-zen1-1-zen
- **Packages**: 1003 (pacman)
- **Display**: 2560x1080 @ 60 Hz in 34" [External], 2560x1080 @ 60 Hz in 34" [External], 1920x1080 @ 60 Hz in 15" [Built-in]
- **Window Manager**: Hyprland (Wayland)
- **Terminal**: kitty 0.36.1
- **CPU**: AMD Ryzen 7 5700U
- **GPU**: Lucienne (Integrated)
- **GPU Driver**: amdgpu
- **Memory**: 6.63 GiB (8 GB - 1,5GB dedicated to GPU)
- **OS Age**: 133 days
- **Hyprland Version**: hyprland-git 0.42.0.r87.92a0dd16-1
- **Aquamarine Version**: aquamarine-git 0.3.3.r16.g561f50b-1
- **Laptop Model**: IdeaPad 5 82LN0026HV
- **Dock Hub Model**: HAMA USB 3.2 Type-C 10 in 1 dock adapter gray
- **External Monitors**: LG 34WP65G-B
- **Hyprland dots and configs**: [prasanthrangan/hyprdots](https://github.com/prasanthrangan/hyprdots)

> **Note:** When the monitor is connected directly to the laptop's HDMI port, Hyprland recognizes it as `HDMI-A-1`. However, when connected through the HAMA Dock Hub, the monitor is identified as `DP-3`.

## Attempted Solutions

1. **Downgrading Hyprland**: I attempted to downgrade Hyprland, but this did not resolve the issue.

2. **Changing to -git**: I attempted to switch to the -git version of Hyprland and Aquamarine, but this did not resolve the issue.

## Current Behavior

When the monitor is plugged into the Dock Hub, the screen remains black and is not detected by the system.

## Additional Information

- The monitor works fine when directly connected to the laptop.
- All other devices connected to the Dock Hub are functioning correctly.
- The system recognizes two displays: one external (2560x1080) and one built-in (1920x1080).

## Requested Help

I'm seeking assistance in troubleshooting and resolving this issue. Any insights into why Hyprland might not be recognizing the monitor through the Dock Hub would be greatly appreciated.

### Hyprland log
  
[hyprland.log](https://github.com/user-attachments/files/16801992/hyprland.log)

### journalctl log

[journalctl.log](https://github.com/user-attachments/files/16801998/journalctl.log)

### dmesg log

[dmesg.log](https://github.com/user-attachments/files/16802002/dmesg.log)

### 'hyprctl monitors all' output (connected directly to laptop):
```bash
  Monitor eDP-1 (ID 0):
	1920x1080@60.00100 at 4480x0
	description: Chimei Innolux Corporation 0x151E
	make: Chimei Innolux Corporation
	model: 0x151E
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 31 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: A XRGB8888 H XRGB8888
	availableModes: 1920x1080@60.00Hz 1680x1050@60.00Hz 1280x1024@60.00Hz 1440x900@60.00Hz 1280x800@60.00Hz 1280x720@60.00Hz 1024x768@60.00Hz 800x600@60.00Hz 640x480@60.00Hz 

  Monitor HDMI-A-1 (ID 1):
	2560x1080@59.97800 at 1920x0
	description: LG Electronics LG HDR WFHD 0x000265D6
	make: LG Electronics
	model: LG HDR WFHD
	serial: 0x000265D6
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 32 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: A XRGB8888 H XRGB8888
	availableModes: 2560x1080@59.98Hz 3840x2160@30.00Hz 3840x2160@29.97Hz 3840x2160@25.00Hz 3840x2160@24.00Hz 3840x2160@23.98Hz 2560x1440@59.95Hz 2560x1080@74.99Hz 2560x1080@50.00Hz 1920x1080@74.99Hz 1920x1080@60.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1680x1050@59.88Hz 1600x900@60.00Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1440x900@59.98Hz 1280x800@59.91Hz 1152x864@59.97Hz 1280x720@60.00Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@75.03Hz 1024x768@60.00Hz 832x624@74.55Hz 800x600@75.00Hz 800x600@60.32Hz 720x576@50.00Hz 720x480@60.00Hz 720x480@59.94Hz 640x480@75.00Hz 640x480@60.00Hz 640x480@59.94Hz 640x480@59.94Hz 
```

### 'hyprctl monitors all' output (connected via hub):
```bash
  Monitor eDP-1 (ID 0):
    1920x1080@60.00100 at 4480x0
    description: Chimei Innolux Corporation 0x151E
    make: Chimei Innolux Corporation
    model: 0x151E
    serial: 
    active workspace: 3 (3)
    special workspace: 0 ()
    reserved: 0 32 0 0
    scale: 1.00
    transform: 0
    focused: yes
    dpmsStatus: 1
    vrr: 0
    activelyTearing: false
    disabled: false
    currentFormat: A XRGB8888 H XRGB8888
    availableModes: 1920x1080@60.00Hz 1680x1050@60.00Hz 1280x1024@60.00Hz 1440x900@60.00Hz 1280x800@60.00Hz   1280x720@60.00Hz 1024x768@60.00Hz 800x600@60.00Hz 640x480@60.00Hz 
```

### 'lsplug' output (connected directly to laptop):
```bash
    USB 1-1  [2109:2817] VIA Labs, Inc. USB2.0 Hub
    USB 1-1.2 [1a40:0101] Terminus Technology Inc. Hub
    USB 1-1.2.4 [2109:0102] VIA Labs, Inc. USB 2.0 BILLBOARD [0000000000000001]
    USB 1-1.5 [2109:8888] VIA Labs, Inc. USB Billboard Device [0000000000000001]
    USB 1-2  [046d:c548] Logitech, Inc. Logi Bolt Receiver
    USB 1-3  [13d3:56ff] IMC Networks Integrated Camera
    USB 2-1  [2109:0817] VIA Labs, Inc. USB3.0 Hub
    USB 3-3  [0cf3:e300] Qualcomm Atheros Communications QCA61x4 Bluetooth 4.0
    USB 3-4  [04f3:0c58] Elan Microelectronics Corp. ELAN:Fingerprint
```

### 'lsplug' output (connected via hub):
```bash
    USB 1-1  [2109:2817] VIA Labs, Inc. USB2.0 Hub
    USB 1-1.2 [1a40:0101] Terminus Technology Inc. Hub
    USB 1-1.2.4 [2109:0102] VIA Labs, Inc. USB 2.0 BILLBOARD [0000000000000001]
    USB 1-1.5 [2109:8888] VIA Labs, Inc. USB Billboard Device [0000000000000001]
    USB 1-2  [046d:c548] Logitech, Inc. Logi Bolt Receiver
    USB 1-3  [13d3:56ff] IMC Networks Integrated Camera
    USB 2-1  [2109:0817] VIA Labs, Inc. USB3.0 Hub
    USB 3-3  [0cf3:e300] Qualcomm Atheros Communications QCA61x4 Bluetooth 4.0
    USB 3-4  [04f3:0c58] Elan Microelectronics Corp. ELAN:Fingerprint
```

### 'xrandr' output (connected directly to laptop):
```bash
  -> HDMI-A-0 connected 2560x1080+1920+0 (normal left inverted right x axis y axis) 798mm x 334mm
     2560x1080     59.98*+
     1920x1080     60.00    50.00    59.94  
     1680x1050     59.88  
     1600x900      60.00  
     1280x1024     75.02    60.02  
     1280x800      59.81  
     1280x720      60.00    50.00    59.94  
     1024x768      75.03    60.00  
     800x600       75.00    60.32  
     720x576       50.00  
     720x480       60.00    59.94  
     640x480       75.00    60.00    59.94  
  
  eDP connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
     1920x1080     60.01*+  60.01    59.97    59.96    59.93  
     1680x1050     59.95    59.88  
     1600x900      59.99    59.94    59.95    59.82  
     1440x900      59.89  
     1400x900      59.96    59.88  
     1368x768      59.88    59.85  
     1280x1024     60.02  
     1280x800      59.99    59.97    59.81    59.91  
     1280x720      60.00    59.99    59.86    59.74  
     1024x768      60.04    60.00  
     960x720       60.00  
     928x696       60.05  
     896x672       60.01  
     864x648       60.00  
     840x525       60.01    59.88  
     800x600       60.00    60.32    56.25  
     700x525       59.98  
     640x512       60.02  
     640x480       60.00    59.94  
     512x384       60.00  
     400x300       60.32    56.34  
     320x240       60.05  
```

### 'xrandr' output (connected via hub):
```bash
  -> eDP connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
     1920x1080     60.01*+  60.01    59.97    59.96    59.93  
     1680x1050     59.95    59.88  
     1600x900      59.99    59.94    59.95    59.82  
     1440x900      59.89  
     1400x900      59.96    59.88  
     1368x768      59.88    59.85  
     1280x1024     60.02  
     1280x800      59.99    59.97    59.81    59.91  
     1280x720      60.00    59.99    59.86    59.74  
     1024x768      60.04    60.00  
     960x720       60.00  
     928x696       60.05  
     896x672       60.01  
     864x648       60.00  
     840x525       60.01    59.88  
     800x600       60.00    60.32    56.25  
     700x525       59.98  
     640x512       60.02  
     640x480       60.00    59.94  
     512x384       60.00  
     400x300       60.32    56.34  
     320x240       60.05  
```

**Comment by fufexan** [comment]
I saw this right as I was getting frustrated with the same issue. Sometimes replugging repeatedly works, but it's very annoying.

**Comment by ikalco** [comment]
if this isn't solved by downgrading to v0.41.2 then it might be a driver issue
I have a feeling recent 6.10 kernel update might be the cause, you should try downgrading to 6.9

**Comment by Da4ndo** [comment]
> if this isn't solved by downgrading to v0.41.2 then it might be a driver issue I have a feeling recent 6.10 kernel update might be the cause, you should try downgrading to 6.9

Could you please provide specific steps or guidance on how to successfully downgrade the entire Linux kernel, because just downgrading the core/linux package doesn't do it exactly.

**Comment by fufexan** [comment]
Looks like I'm experiencing the same things even with Linux 6.6.

**Comment by ikalco** [comment]
I saw this in the logs, it might be related
>[LOG] [AQ] udev: DRM device card1 change event unrecognized

can you give a log of plugging/unplugging with
`sudo udevadm monitor --kernel --udev --property`

**Comment by Da4ndo** [comment]
I ran the code, unplugged HDMI cable for Monitor from Hub and replugged. Here is the log for hyprland:
[hyprland.log](https://github.com/user-attachments/files/16805122/hyprland.log)

**Comment by ikalco** [comment]
I meant copy the output of the command
or write to file like
`sudo udevadm monitor --kernel --udev --property >~/log.txt 2>&1`

**Comment by Da4ndo** [comment]
I also thought that but it didn't write out anything. Thats why I though sending the log.

**Comment by ikalco** [comment]
try removing the --kernel
i was typing it from memory so that might be wrong

**Comment by Da4ndo** [comment]
![image](https://github.com/user-attachments/assets/bf8b0ed1-33e3-43fe-9f26-adca49870b55)

**Test Results:**
- The first test was with the Hub, but the command did not provide any output.
- The second method involved plugging straight into the laptop.

**Urgent Request:**
Can we try to resolve this issue because it affects more than just myself, and I absolutely need my two monitors to be connected so that I can work. I can't work efficiently this way, so I'd appreciate a quick repair. 

Thank you beforehand.

**Comment by ikalco** [comment]
no udev events means the kernel didn't detect you plugging into the hub...
does this work on other compositors? like sway or kde?

**Comment by Da4ndo** [comment]
**I tested the Hub on a Windows laptop with the same monitor via HDMI, and it worked.** This worked on the hyprland previously, as I mentioned, but when the new update for hyprland to utilize aquamarine and the new kernel version arrived, it broke.

**Comment by vaxerski** [comment]
test kde or sway, we dont really care about windows

**Comment by Da4ndo** [comment]
> test kde or sway, we dont really care about windows

I cannot test on those. I don't have anything using them that I can test on. Please understand.

**Comment by Da4ndo** [comment]
Sorry, I don't hav any real fix, however most recent update fixed it for me, and my monitor now works. Thank you everybody for the help so far.
