### ISSUE TITLE
Crash on start after 865cd94

### ISSUE THREAD

**Issue by davc0n** [hyprwm/aquamarine#70]
Hello,

The problem has been introduced with the commit 865cd94.
Session gets closed right after hyprland launch.

```
Aug 31 18:57:05 thinkpad pipewire[724]: spa.v4l2: Cannot open '/dev/video2': 13, Permission denied
Aug 31 18:57:05 thinkpad pipewire[724]: spa.v4l2: Cannot open '/dev/video0': 13, Permission denied
```

**Comment by vaskark** [comment]
+1

**Comment by vaxerski** [comment]
can't repro crashes. Can I get a debug stacktrace? https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by vaskark** [comment]
> can't repro crashes. Can I get a debug stacktrace? https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

@vaxerski  I should have mentioned I'm using the binary release on Ubuntu 24.04.01. Will the stacktrace still work?

**Comment by vaxerski** [comment]
well then your problem is likely unrelated

**Comment by ferrreo** [comment]
I am getting the same crash too when using latest git, I'll try and get a stacktrace

**Comment by ferrreo** [comment]
@vaxerski Here is the stacktrace for you fella. 
[gdb.txt](https://github.com/user-attachments/files/16828648/gdb.txt)

**Comment by vaxerski** [comment]
you forgot to build aquamarine in debug :(

**Comment by ferrreo** [comment]
I think think this one has aquamarine in debug, I did cmake --build ./build --config Debug --target all -j32 then the install
[gdb.txt](https://github.com/user-attachments/files/16829075/gdb.txt)

**Comment by vaxerski** [comment]
nope:
```
#7  0x0000000595eb6cab in ??? ()
#8  0x000072e97af6dc82 in Aquamarine::CSwapchain::reconfigure(Aquamarine::SSwapchainOptions const&) () at /lib/x86_64-linux-gnu/libaquamarine.so.2
```

you likely duped aquamarine libs

remove all libaquamarine (in /usr/lib or /usr/local/lib) and do
```
cmake -DCMAKE_INSTALL_LIBEXECDIR=/usr/lib -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE:STRING=Debug -B build
cmake --build build -j `nproc`
```

then `sudo cmake --install build`

then compile hl in debug

then get bt

**Comment by ferrreo** [comment]
[gdb.txt](https://github.com/user-attachments/files/16829856/gdb.txt)

Ok looks more like a proper trace now

**Comment by vaxerski** [comment]
this looks to me like you recompiled aquamarine without recompiling hyprland afterwards

**Comment by ferrreo** [comment]
Yeah I missed a make clear before compiling hl doh! It is working perfectly fine now for me.
