### ISSUE TITLE
Weird color range on HDMI outputs

### ISSUE THREAD

**Issue by PancakeTAS** [hyprwm/aquamarine#75]
For some reason every monitor connected through HDMI has incorrect colors. It looks like they are caused by incorrect color range (limited rgb vs full rgb). Issue occurs on 8-bit and 10-bit output :P

No clue if this is caused by Hyprland, aquamarine, nvidia drivers or who knows what, but I hope there's a fix to be found..

Attached `proptest -M nvidia-drm -D /dev/dri/renderD128`, because I saw some random person on the internet try to fix it with this tool, lol (fix was unsuccessful on nvidia, seems like "Broadcast RGB" is not a thing over here)
[proptest.txt](https://github.com/user-attachments/files/16841815/proptest.txt)

**Comment by vaxerski** [comment]
two things:
 - have you checked sway or kwin
 - is this a regression, aka does it happen on 0.39.1 or 0.41?

**Comment by Edgars-Cirulis** [comment]
> The issue also exists on sway, I couldn't check kwin and it does not appear to be a regression. It would be really nice if someone else could also try to reproduce this? I really don't want to believe I am the only Wayland user that has an HDMI monitor on NVIDIA.

HDR enabled? If yes, it has color washout bug..

**Comment by PancakeTAS** [comment]
My monitor does not support HDR output, nor does aquamarine as far as I know. Besides, the colors aren't actually washed out, but super vibrant as you would get from incorrect color range

**Comment by PancakeTAS** [comment]
welp, I can reproduce this on windows LMAO

closing as driver issue..
