### ISSUE TITLE
Crash when starting Hyprland on a Thinkpad T60

### ISSUE THREAD

**Issue by networkuka** [hyprwm/aquamarine#79]
I'm trying to use hyprland on a Thinkapd T60 with 3gb of ram, a T5600 and an ATI x1300 but I encountered a bug with aquamarine I think. Also, I'm using gentoo and compiled hyprland with legacyrenderer. Here is the crash report (the crash report is from wednesday september 4, I forgot to set the date on the laptop) :
[crash_legacyrenderer.txt](https://github.com/user-attachments/files/16897662/crash_legacyrenderer.txt).

**Comment by vaxerski** [comment]
update aq and hl
