### ISSUE TITLE
Can't complete make on Hyprland because can't find aquamarine

### ISSUE THREAD

**Issue by MrSloth-dev** [hyprwm/aquamarine#90]
Hello,
I'm on Ubuntu and I'm trying to build Hyprland and one thing that is blocking the progress is that I can't complete the make execution and this message appears
```
CMake Error at /usr/local/share/cmake-3.30/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - aquamarine

Call Stack (most recent call first):
  /usr/local/share/cmake-3.30/Modules/FindPkgConfig.cmake:873 (_pkg_check_modules_internal)
  CMakeLists.txt:103 (pkg_check_modules)
```
Is there a way to check if aquamarine is correctly installed? `whereis` and `which` don't help.

This is my first time reporting an issue in GH, so if you need any more info, let me know.

Best Regards.

**Comment by vaxerski** [comment]
> Is there a way to check if aquamarine is correctly installed?

`pkg-config --path aquamarine`

**Comment by MrSloth-dev** [comment]
well, it appeared nothing. After I tried again, I notice that `epoll-shim` was not found. I missed that line and maybe it's that. I'm have problems now installed epoll-shim, heading there... good work and thank you for your time.

**Comment by vaxerski** [comment]
I'll close this as it isnt an issue with our code
