### ISSUE TITLE
Explanation of primary/backup GPU and possible support for GPU unbinding?

### ISSUE THREAD

**Issue by LukeXuan** [hyprwm/aquamarine#91]
Disclaimer: I know nothing about the inner working of DRM rendering.

Aquamarine supports running multiple GPUs (automatically or through `AQ_DRM_DEVICES`), and in the log it will show one GPU is used as the primary and the other one used as secondary. In practice, I never noticed any difference from just having the primary GPU enabled (except for the display ports on the second GU). Could you explain more when are secondary GPUs going to be used?

Another more involved question is whether you believe it is possible to support GPU unbinding when Hyprland/Aquamarine is running as long as the device list is not empty? By support I mean either adding a command like `hyprctl unbind` (more likely) or detecting device changes automatically without crashing Hyprland (fancy but I assume less likely).

**Comment by vaxerski** [comment]
secondary gpu is used as a bridge to access more outputs.

In many cases (e.g. laptops) the display ports are wired to the dGPU exclusively, so we have to render on the primary gpu, and then use it to render it to the secondary gpu, so that it can display it via the port.

> Another more involved question is whether you believe it is possible to support GPU unbinding when Hyprland/Aquamarine is running as long as the device list is not empty? By support I mean either adding a command like hyprctl unbind (more likely) or detecting device changes automatically without crashing Hyprland (fancy but I assume less likely).

technically, yes. But practically, I fail to see a useful scenario that would benefit from this, and it's not worth the effort for me

**Comment by vaxerski** [comment]
> The other alternative is to not use discrete GPU for hyprland at all (for other applications, I can use DRI_PRIME=1 to adjust). Sadly my integrated GPU is not that powerful and I can see significant frame drop for mouse movement when there are blurred/transparent windows.

force your igpu to constantly run at max clock, (unless you really care about battery life) igpus do be like that
