### ISSUE TITLE
Runtime error when compiling with libc++

### ISSUE THREAD

**Issue by fabolous005** [hyprwm/aquamarine#93]
When compiling libc++ with `--stdlib=libc++` and clang it results in the following [crash report](https://github.com/user-attachments/files/17282792/hyprlandCrashReport19756.txt).
Are you planing to support this?

**Comment by vaxerski** [comment]
I'll need a debug stacktrace. https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by vaxerski** [comment]
launch hyprland with gdb then and follow the same instructions for a backtrace when it crashes

**Comment by 0xC0ncord** [comment]
I had this exact crash but only with Aquamarine 0.4.2 built with clang/LLVM 19.1.2, but not any prior version. Recompiling AQ without LTO fixed it for me.
