### ISSUE TITLE
Hyprland seg fault

### ISSUE THREAD

**Issue by vaskark** [hyprwm/aquamarine#98]
Crash report: [0x0.st/X6Ge.txt](https://0x0.st/X6Ge.txt)

Ubuntu 24.10
Hyprland 0.44.1 (binary)
aquamarine: latest git

Thanks.

**Comment by vaxerski** [comment]
please get a debug stacktrace https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace

**Comment by vaskark** [comment]
Sorry about that. Should have known.
It was a binary release, I didn't build.

coredumpctl debug Hyprland: [link](https://0x0.st/X6Dg.txt)

**Comment by vaxerski** [comment]
that's info not debug

**Comment by vaskark** [comment]
Thanks for your patience. I've never done this before. And I didn't have gdb.

[gdb.txt](https://0x0.st/X6kz.txt)

**Comment by vaskark** [comment]
```
cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -S . -B ./build
cmake --build ./build --config Debug --target all -j`nproc 2>/dev/null || getconf _NPROCESSORS_CONF`
```

I changed Release to Debug and reinstalled ... and now Hyprland no longer crashes.
I'm kinda confused at this point. But at least I'm  back in.

Many thanks.

**Comment by vaxerski** [comment]
maybe your aq was compiled incorrectly or against wrong mesa? Anyways, closing then, feel free to reopen if it happens again
